[build-system]
requires = [
    "setuptools>=61.0",
    "setuptools_scm[toml]>=6.2",
    "cmake>=3.15",
    "pybind11>=2.12.0",
    "cython>=3.0.10",
    "numpy>=2.0.0rc1",
    "ninja>=1.10.0"

]
build-backend = "setuptools.build_meta"

[project]
name = "sudio"
license = {file = "LICENSE"}
version = '1.0.11'
description = "Audio Processing Platform"
authors = [{name = "Hossein Zahaki", email = "mrzahaki@gmail.com"}]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    'Development Status :: 6 - Mature',
    "Intended Audience :: Developers",
    'Intended Audience :: Science/Research',
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Programming Language :: C",
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3 :: Only',
    'Programming Language :: Python :: Implementation :: CPython',
    'Topic :: Software Development',
    "Typing :: Typed",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Operating System :: MacOS",
]
dependencies = [
    "scipy>=1.10.0",
    "numpy>=1.26.0",
]
[project.urls]
repository = "https://github.com/mrzahaki/sudio"
documentation = "https://mrzahaki.github.io/sudio/"

[project.optional-dependencies]

test = [
    'pytest>=7.3.2', 
    'pytest-xdist>=3.4.0', 
    "Cython", 
    'ninja; sys_platform != "emscripten"',
]
doc=[
    "sphinx>=5.0.0",
    "sphinx-rtd-theme>=1.0.0",
    "sphinx-autodoc-typehints>=1.18.0",
    "sphinxcontrib-napoleon>=0.7",
    "breathe>=4.34.0",
    "exhale>=0.3.5",
    "numpy>=1.26.0",
]


[tool.cibuildwheel]
build-frontend = "build"
skip = "cp36-* cp37-* cp38-* pp37-* *-manylinux_i686 *_ppc64le *_s390x *_universal2"
config-settings = "setup-args=-Duse-ilp64=true setup-args=-Dallow-noblas=false build-dir=build"
environment = {LDFLAGS="-Wl,--strip-all"}
test-requires = [
    "pytest",
    "pytest-xdist",
    "hypothesis",
]
build-verbosity = 0
test-command = """
  python -c 'import sudio as su; \
  sys.exit(not su.test(extra_argv=['--durations=0'])); \
  """

[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux2014"
manylinux-aarch64-image = "manylinux2014"
musllinux-x86_64-image = "musllinux_1_2"
# before-all = "yum install -y python3-devel"

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-test = "apk update && apk add musl-locales"

[tool.pytest.ini_options]
minversion = "7.3.2"
xfail_strict = true
testpaths = "sudio"
